name: EasyWarps
version: '1.0'
main: me.lostoryt.easyWarps.Main
api-version: '1.21'
commands:
  setspawn:
    description: This command set spawn in any location
    usage: /<command> [id]
  spawn:
    description: This command teleport player on spawn
    usage: /<command> [id]
  delspawn:
    description: This command delete spawn
    usage: /<command> [id]

  setwarp:
    description: This command set warp in any location
    usage: /<command> <name>
  warp:
    description: This command teleport player to warp with his name
    usage: /<command> <name>
  delwarp:
    description: This command delete warp with his name
    usage: /<command> <name>
  warps:
    description: This command open warps gui
    usage: /<command>

permissions:
  easywarps.setspawn:
    description: Permission on command /setspawn
    default: op
  easywarps.spawn:
    description: Permission on command /spawn
    default: true
  easywarps.delspawn:
    description: Permission on command /delspawn
    default: op

  easywarps.setwarp:
    description: Permission on command /setwarp
    default: true
  easywarps.warp:
    description: Permission on command /warp
    default: true
  easywarps.delwarp:
    description: Permission on command /delwarp
    default: op
  easywarps.warps:
    description: Permission on command /warps
    default: true